name: CICD
on:
  push:
    branches:
      - main
    tags:
      - '*'
env:
  IMAGE_NAME: littlelucidlynx/static-nginx-app
  IMAGE_TAG: ${{ github.run_number }}
  RELEASE_NAME: myapp
  NAMESPACE: monitoring

jobs:

  build:
    outputs:
      image_tag: ${{ env.IMAGE_TAG }}
    runs-on: ubuntu-latest

    steps:
    
    - name: Get files
      uses: actions/checkout@v3

    - name: Set env IMAGE_TAG
      id: step_tag
      run: echo "IMAGE_TAG=$(echo ${GITHUB_REF:10})" >> $GITHUB_ENV
      if: startsWith(github.ref, 'refs/tags/v')
      
    - name: Build the Docker image
      run: docker build . --file ./Dockerfile --tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
    
    - name: Push the Docker image
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
