name: CI

on:
  push:
    branches:
    - main
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Get files
      uses: actions/checkout@v3

    - name: build+push
      if: ${{ github.ref_name == '' }}
      run: echo "NO TAG"

    - name: build+push+deploy
      if: startsWith(github.ref, 'refs/tags/v')
      run: echo "v TAG"
